{% set version = "1.1.0" %}

package:
  name: rst2txt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rst2txt/rst2txt-{{ version }}.tar.gz
  sha256: ded9e4fb2686f039eb06c0608980fd13982998ce365a9d008a495649ed85f7cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - rst2txt = rst2txt:main

requirements:
  host:
    - pip
    - python >=3.4
    - setuptools >=30.3.0
    - setuptools-scm
  run:
    - docutils >=0.11
    - pygments
    - python >=3.4

test:
  requires:
    - pip
  imports:
    - rst2txt
  commands:
    - pip check
    - rst2txt --help

about:
  home: https://github.com/stephenfin/rst2txt
  summary: Convert reStructuredText to plain text
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
